---
#
# Download and install Zimbra OSE
################################################################################

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts 
    line: "{{ item }}" 
    state: present
  with_items: "{{ hosts_lines }}"
  when: hosts_lines is defined

- name: Set Zimbra OSE {{ zimbra_version }} build name
  set_fact:
    zm_pkg: "{{ zm_repo[zimbra_version].builds[ansible_distribution | lower][ansible_distribution_major_version | int] }}"
  
- name: Download and unpacking Zimbra OSE {{ zimbra_version }}
  unarchive:
    validate_certs: no
    src: '{{ zm_repo[zimbra_version].url }}{{ zm_pkg }}.tgz'
    dest: /usr/local/src/
    copy: no

- name: Create the folder to upload the scripts
  file:
    path: /tmp/zcs
    state: directory

- name: Uploading keystroke file
  template:
    src: "{{ 'installZimbra-keystrokes' if not zimbra_upgrade else 'installZimbraUpgrade-keystrokes' }}"
    dest: /tmp/zcs/installZimbra-keystrokes
    owner: root
    group: root
    mode: 0644

- name: Uploading installer configuration file
  template:
    src: "{{ 'installZimbraScript.j2' if not zimbra_upgrade else 'installZimbraScriptUpgrade.j2' }}"
    dest: /tmp/zcs/installZimbraScript
    owner: root
    group: root
    mode: 0644

- name: Installing Zimbra OSE {{ zimbra_version }}
  shell: ./install.sh -s < /tmp/zcs/installZimbra-keystrokes
  args:
    chdir: '/usr/local/src/{{ zm_pkg }}/'

- name: Configuring Zimbra OSE's services for use
  command: ./zmsetup.pl -c /tmp/zcs/installZimbraScript
  args:
    chdir: /opt/zimbra/libexec/
